== 3 Strings
=== 3.4 Top-level versus local definitions
==== Exercises: Scope

.1 These lines of code are from a REPL session. Is `y` in scope for `z`? --> yes

[source]
-----
Prelude> let x = 5
Prelude> let y = 7
Prelude> let z = x * y
-----

.2 These lines of code are from a REPL session. Is `h` in scope for `g`? Go with your gut here --> no

[source]
-----
Prelude> let f = 3
Prelude> let g = 6 * f + h
-----

.3 These lines of code are from a REPL session. Is everything we need to execute area in scope --> no

[source]
-----
area d = pi * (r * r)
r = d / 2
-----

.4 These lines of code are from a REPL session. Now are `r` and `d` in scope for `area` --> ok

[source]
-----
area d = pi * (r * r)
  where r = d / 2
-----

=== 3.5 Types of concatenation functions
==== Exercises: Syntax Errors

Read the syntax of the following functions and decide whether it will compile. Test them in your REPL and try to fix the syntax errors where they occur.

.1 `++ [1, 2, 3] [4, 5, 6]` --> `concat [[1, 2, 3] [4, 5, 6]]`
.2 `'<3' ++ ' Haskell'`  --> `"<3" ++ " Haskell"`
.3 `concat ["<3", " Haskell"]` --> ok

=== 3.8 Chapter Exercises
==== Exercises: Reading syntax
.1 For the following lines of code, read the syntax carefully and decide if they are written correctly. Test them in your REPL after you’ve decided to check your work. Correct as many as you can.

[source]
-----
-- a) 
concat [[1, 2, 3], [4, 5, 6]] -- ok
-- b) 
++ [1, 2, 3] [4, 5, 6] -- ko
-- c) 
(++) "hello" " world" -- ok
-- d) 
["hello" ++ " world] -- ko
-- e) 
4 !! "hello" -- ko
-- f) 
(!!) "hello" 4 -- ok
-- g) 
take "4 lovely" -- ko
-- h) 
take 3 "awesome" -- ok
-----

.2 Next we have two sets: the first set is lines of code and the other is a set of results. Read the code and figure out which results came from which lines of code. Be sure to test them in the REPL.
[source]
-----
-- a) 
concat [[1 * 6], [2 * 6], [3 * 6]] -- match `[6,12,18]`
-- b) 
"rain" ++ drop 2 "elbow" -- match `"rainbow"`
-- c) 
10 * head [1, 2, 3]` -- match `10`
-- d) 
(take 3 "Julie") ++ (tail "yes") -- match `"Jules"`
-- e) 
concat [tail [1, 2, 3], tail [4, 5, 6], tail [7, 8, 9]] --> match `[2,3,5,6,8,9]`
-----

==== Exercises: Building functions
. String/list manipulation functions (includes 1 and 2)
[source]
----
include::ch03.8B_2.hs[]
----

. `*thirdLetter*`
[source]
----
include::ch03.8B_3.hs[]
----

