== 2 Hello, Haskell!
=== 2.5 Evaluation
==== Comprehension Check
Given the following lines of code they might appear in a source file, how would you change them to use them directly in the REPL?
. 1) `half x = x / 2` -> `let half x = x / 2`
. 2) `square x = x * x` `let square x = x * x`

Write one function that can accept one argument and work for all the following expressions. Be sure to name the functions
. - `3.14 * (5 * 5)`
. - `3.14 * (10 * 10)`
. - `3.14 * (2 * 2)`
. - `3.14 * (4 * 4)`

[source]
----
dpi x = 3.14 * x * x
dpi x = pi * x * x
----

==== Exercises: Parentheses and Association
. 1 different
+ 
[source]
----
8 + 7 * 9
(8 + 7) * 9
----

. 2 same
+
[source]
----
perimeter x y = (x * 2) + (y * 2)
perimeter x y = x * 2 + y * 2
----

. 3 different
+
[source]
----
f x = x / 2 + 9
f x = x / (2 + 9)
----

=== 2.7 Declaring values
==== Heal the Sick
. 1
[source] wrong
----
let area x = 3. 14 * ( x * x)
----

[source] correct
----
let area x = 3.14 * ( x * x)
----

. 2
[source] wrong
----
let double x = b * 2
----

[source] correct
----
let double x = x * 2
----

. 3
[source] wrong
----
x = 7 
 y = 10
f= x + y
----

[source] correct
----
x = 7 
y = 10
f= x + y
----

=== 2.10 Let and where
==== Exercises: A Head Code
. 1 -> 5?
[source]
----
let x = 5 in x
----

. 2 -> 25?
[source]
----
let x = 5 in x * x
----

. 3 -> 30?
[source]
----
let x = 5; y = 6 in x * y
----

. 4 -> 3?
[source]
----
let x = 3; y = 1000 in x + 3
----

=== 2.11 Chapter Exercises
==== Parenthesization
. 1
[source]
----
2 + 2 * 3 - 1 == 2 + (2 * 3) - 1
----

. 2
[source]
----
(^) 10 $ 1 + 1
(^) 10 (1 + 1)
----

. 3
[source]
----
(^) 10 $ 1 + 1
(^) 10 (1 + 1)
----

. 4
[source]
----
2 ^ 2 * 4 ^ 5 + 1 == (2 ^ 2) * (4 ^ 5) + 1
----

==== Equivalent expressions

. 1 -> equivalent
[source]
----
1 + 1
2
----

. 2 -> equivalent (same of 10 + (9 * 10))
[source]
----
10 ^ 2
10 + 9 * 10
----

. 3 -> not equivalent (not commutative)
[source]
----
400 - 37
(-) 37 400
----

. 4 -> not equivalent (div returns an Integer, check :info `div` and :info / in the repl)
[source]
----
100 `div` 3
100 / 3
----

. 5 -> not equivalent (the first expression is equal to (2 * 5) + 18)
[source]
----
2 * 5 + 18
2 * (5 + 18)
----

==== More fun with functions

[source]
----
let z = 7
let y = z + 8
let x = y ^ 2
let waxOn = x * 5  -- 1125
----

. 1
[source]
----
10 + waxOn -- 1135
(+10) waxOn -- 1135 
(-) 15 waxOn -- -1110
(-) waxOn 15 -- 1110
----

. 2
[source]
----
let triple x = x * 3
----

. 3
[source]
----
triple waxOn -- 3375
----

. 4 -- practices.hs
[source]
----
waxOn = x * 5
  where x = y ^ 2
        y = z + 8
        z = 7
----

. 5
[source]
----
triple x = x * 3
----

. 6
[source]
----
waxOff x = triple x
----

. 7
[source]
----
waxOff waxOn -- 3375
waxOff 10    -- 30
waxOff (-50) -- -150
waxOff2 x = triple x ^ 2
waxOff3 x = triple x / 10
----