== 4 Basic datatypes
=== 4.3 Anatomy of a data declaration
==== Exercises: Mood Swing

Given:

[source]
----
data Mood = Blah | Woot deriving Show
----

. 1
type constructor -> Mood

. 2
possible `Mood` values -> `Blah`, `Woot`

. 3
`changeMood :: Mood -> Woot` --> signature should be `changeMood :: Mood -> Mood`

. 4
[source]
----
changeMood :: Mood -> Mood

changeMood Blah = Woot
changeMood    _ = Blah
----

. 5
[source]
----
include::ch04.3_5.hs[]
----

=== 4.9 Chapter Exercises
==== Exercises

Start having in your REPL:

[source]
----
let awesome = ["Papuchon", "curry", ":)"] 
let also = ["Quake", "The Simons"] 
let allAwesome = [awesome, also]
----

. 1 

Given the definition of length above, what would the type signature be? 
How many arguments, of what type does it take? What is the type of the result it evaluates to?
[source]
----
length :: [a] -> Integer
----

. 2
What are the results of the following expressions?
[source]
----
length [1, 2, 3, 4, 5] -- -> 5
length [(1, 2), (2, 3), (3, 4)] -- -> 3
length allAwesome -- -> 2
length (concat allAwesome) -- -> 5
----

. 3
Given what we know about numeric types and the type signature of length, look at these two expressions. One works and one returns an error. 
Determine which will return an error and why.
(n.b., you will find `Foldable t => t a` representing `[a]`, as with concat in the previous chapter. 
Again, consider `Foldable t` to represent a list here, even though list is only one of the possible types.)

[source]
----
6 / 3 -- -> ok
-- and
6 / length [1, 2, 3] -- -> error: length returns an integer and not a fractional.
----

. 4
fix (3)

[source]
----
6 / length [1, 2, 3]
----

. 5
[source]
----
2 + 3 == 5 :: Bool
(2 + 3 == 5) == True
----

. 6 type and result expected
[source]
----
let x = 5
(x + 3 == 5) == False :: Bool
----

. 7 which will work or not
[source]
----
length allAwesome == 2 -- -> ok
length [1, 'a', 3, 'b'] -- -> ko types array elements missmatch
length allAwesome + length awesome -- -> ok 5
(8 == 8) && ('b' < 'a') --> ok False
(8 == 8) && 9 --> ko 9 not Bool
----

 .8 Write a function that tells you whether or not a given String (or list) is a palindrome
[source]
----
isPalindrome :: (Eq a) => [a] -> Bool 
isPalindrome x = x == reverse x
----

. 9 Write a function to return the absolute value of a number using if-then-else
[source]
----
myAbs :: Integer -> Integer 
myAbs x = if x > 0 then x else -x
----

. 10 Fill in the definition of the following function, using `fst` and `snd`:
[source]
----
f :: (a, b) -> (c, d) -> ((b, d), (a, c)) 
f a b = ((snd a, snd b),(fst a, fst b))
----

==== Correcting syntax

. 1 we want a function that adds 1 to the length of a string argument and returns that result.
[source]
----
x = (+)
f xs = w `x` 1
    where w = length xs
----

. 2 This is supposed to be the identity function, id. `\X = x`
[source]
----
myId x = x
----

. When  xed, this function will return `1` from the value `(1, 2)`. 
`f (a b) = A`
[source]
----
myHead (a, b) = a
myHead (1, 2) == 1
----

==== Match the function names to their types
. 1 Which of the following types is the type of show? --> c
a) `show a => a -> String`
b) `Show a -> a -> String`
c) `Show a => a -> String`

. 2 Which of the following types is the type of (==)? --> b
a) `a -> a -> Bool`
b) `Eq a => a -> a -> Bool`
c) `Eq a -> a -> a -> Bool`
d) `Eq a => A -> Bool`

. 3 Which of the following types is the type of fst? --> a
a) `(a, b) -> a`
b) `b -> a`
c) `(a, b) -> b`
. 4 Which of the following types is the type of (+)? --> d
a) `(+) :: Num a -> a -> a -> Bool`
b) `(+) :: Num a => a -> a -> Bool`
c) `(+) :: num a => a -> a -> a`
d) `(+) :: Num a => a -> a -> a`
e) `(+) :: a -> a -> a`


